### ISSUE TITLE
Unable to install extensions in slicer-plus

### ISSUE THREAD

**Issue by AHarouni** [pieper/SlicerDockers#4]
Thanks a lot for creating this git and dockers.
I followed the builds and managed to have slicer in the novnc. I am interested in preinstalling  MONAILabel plugin. 
it seems the install-slicer-extension.py is for older slicer so I changed it to 
```
import os
import time
extensionName = os.environ['EXTENSION_TO_INSTALL']
print(f"installing----- {extensionName}")
manager = slicer.app.extensionsManagerModel()

manager.updateExtensionsMetadataFromServer(True, True)
if not manager.downloadAndInstallExtensionByName(extensionName, True):
  raise ValueError(f"Failed to install {extensionName} extension")
else:
  print(f"installed correctly")
print(f"waiting for installation sleep 10 ")
time.sleep(10)

print(f"exiting  ")
exit()

```
This seems to run without errors but I still when I open slicer it doesn't have the plugin installed. 
Any thoughts ?

**Comment by pieper** [comment]
I believe it's because of missing the second `True` in the args to `downloadAndInstallExtensionByName` which should be the flag to wait for the installation to finish.  `time.sleep(10)` is not a reliable way to do it. 

See the latest script example:

https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#download-and-install-extension

If you get this updated and working for new slicer a pull request would be great, thanks 👍

**Comment by AHarouni** [comment]
Hi @pieper 

You were right on. It worked by simply adding the a second True as 
```
if not manager.downloadAndInstallExtensionByName(extensionName, True, True):
```
I will try to get a PR, I need to clone and test separately since I had this as a small part of a much complicated Dockerfile

**Comment by pieper** [comment]
Have you had any luck with this?

**Comment by AHarouni** [comment]
yes @pieper, your solution worked. 
I guess I got tied up into other things and never got a chance to do this PR.
