### ISSUE TITLE
How to add a password to novnc session?

### ISSUE THREAD

**Issue by AHarouni** [pieper/SlicerDockers#5]
Hi 
This is a great repo. Thanks for creating it. This works great and I have slicer preinstalled in the novnc. This is very useful for lab to show students slicer without installing anything.
however if you know the url and port I immediately an in novnc and see slicer. Is there a way to add a password? ideally as an environment variable while launching the docker container as in similar novnc dockers

**Comment by pieper** [comment]
You can definitely set up vnc to require a password, but I don't think there's a way to set it via an environment variable.  If someone wants to investigate and submit a patch that would be welcome.

The way I usually do security is to expose the novnc port only on localhost and require users to create an ssh tunnel to the machine (so they connect to their localhost).  This provides "industrial strength" security in a way vnc passwords don't, and it means you can use regular machine administration tools for managing users.  It means giving a login account on the host machine, but it can be very locked down except having access to the port.

I'm going to close this as an issue since I don't see adding password support to these images, but feel free to keep posting if you want to discuss usage scenarios.
